#!/usr/bin/env node
'use strict';
/**
 * build-codex.js — generate the Codex distribution from the Claude Code source.
 *
 * The skills are the same text. What differs between hosts:
 *   - the variable naming the skill's own directory
 *     (CLAUDE_SKILL_DIR vs CODEX_SKILL_DIR)
 *   - frontmatter fields Codex does not read (allowed-tools,
 *     disable-model-invocation, argument-hint), which are stripped so a
 *     strict parser cannot trip on them
 *   - hooks.json needs Codex's feature flag documented alongside it
 *
 * Generated, never hand-edited: one source of truth stays in skills/.
 * Run `npm run build:codex` after changing any skill.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'skills');
const OUT = path.join(ROOT, 'codex');

// Codex reads name and description; the rest are Claude Code's.
const DROP_FIELDS = ['allowed-tools', 'disable-model-invocation', 'argument-hint', 'user-invocable'];

function splitFrontmatter(raw) {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) return { fm: null, body: raw };
  return { fm: m[1], body: m[2] };
}

function portFrontmatter(fm) {
  const lines = fm.split('\n');
  const kept = [];
  let dropping = false;
  for (const line of lines) {
    const key = (line.match(/^([a-zA-Z-]+):/) || [])[1];
    if (key) {
      dropping = DROP_FIELDS.includes(key);
      if (dropping) continue;
      kept.push(line);
    } else if (!dropping) {
      kept.push(line); // continuation of a folded value
    }
  }
  return kept.join('\n');
}

function portBody(body) {
  // Codex runs commands from the project root and installs skills to several
  // possible paths, so an absolute skill-relative path is unreliable. The
  // installer puts a small `attic` launcher on PATH instead; every command
  // becomes a plain `attic ...` call that works from anywhere.
  return body
    .replace(/node "\$\{CLAUDE_SKILL_DIR\}\/\.\.\/\.\.\/scripts\/attic-stats\.js"/g, 'attic stats')
    .replace(/node "\$\{CLAUDE_SKILL_DIR\}[^"]*attic\.js"/g, 'attic')
    .replace(/\$\{CLAUDE_SKILL_DIR\}\/\.\.\/attic\//g, '$(attic --skills-dir)/attic/')
    .replace(/\$\{CLAUDE_SKILL_DIR\}\//g, '$(attic --skills-dir)/attic/')
    .replace(/\bCLAUDE_PROJECT_DIR\b/g, 'CODEX_PROJECT_DIR');
}

function copyTree(from, to, transform) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) copyTree(src, dst, transform);
    else if (entry.name.endsWith('.md') && transform) fs.writeFileSync(dst, transform(fs.readFileSync(src, 'utf8')));
    else fs.copyFileSync(src, dst);
  }
}

function portSkill(raw) {
  const { fm, body } = splitFrontmatter(raw);
  if (!fm) return portBody(raw);
  return `---\n${portFrontmatter(fm)}\n---\n${portBody(body)}`;
}

function main() {
  fs.rmSync(OUT, { recursive: true, force: true });
  const skillsOut = path.join(OUT, 'skills');
  fs.mkdirSync(skillsOut, { recursive: true });

  const names = fs.readdirSync(SRC).filter((d) => fs.existsSync(path.join(SRC, d, 'SKILL.md')));
  for (const name of names) {
    copyTree(path.join(SRC, name), path.join(skillsOut, name), portSkill);
  }

  // Installer ships alongside the payload.
  const inst = path.join(ROOT, 'codex-src', 'install.sh');
  if (fs.existsSync(inst)) {
    fs.copyFileSync(inst, path.join(OUT, 'install.sh'));
    fs.chmodSync(path.join(OUT, 'install.sh'), 0o755);
  }

  // The launcher that puts `attic` on PATH.
  const binSrc = path.join(ROOT, 'codex-src', 'bin');
  if (fs.existsSync(binSrc)) {
    copyTree(binSrc, path.join(OUT, 'bin'), null);
    fs.chmodSync(path.join(OUT, 'bin', 'attic'), 0o755);
  }

  // attic-stats.js lives outside skills/, so ship it alongside.
  fs.mkdirSync(path.join(OUT, 'scripts'), { recursive: true });
  for (const f of ['attic-stats.js', 'attic-merge.js']) {
    fs.copyFileSync(path.join(ROOT, 'scripts', f), path.join(OUT, 'scripts', f));
  }

  // Hooks are shared verbatim: the stdin/stdout contract matches.
  copyTree(path.join(ROOT, 'hooks'), path.join(OUT, 'hooks'), null);

  const hooksJson = JSON.parse(fs.readFileSync(path.join(ROOT, 'hooks', 'hooks.json'), 'utf8'));
  const ported = JSON.parse(JSON.stringify(hooksJson).replace(/\$\{CLAUDE_PLUGIN_ROOT\}/g, '${ATTIC_HOME}'));
  ported.description = 'Attic hooks for Codex. Set ATTIC_HOME to the directory holding hooks/. Requires [features] hooks = true in config.toml.';
  fs.writeFileSync(path.join(OUT, 'hooks', 'hooks.json'), JSON.stringify(ported, null, 2) + '\n');

  fs.writeFileSync(path.join(OUT, 'GENERATED'), [
    'This directory is generated by scripts/build-codex.js.',
    'Edit skills/ and hooks/ at the repository root, then run:',
    '',
    '  npm run build:codex',
    '',
    'Hand edits here are overwritten.',
    '',
  ].join('\n'));

  console.log(`codex/: ${names.length} skills + hooks`);
  return names;
}

if (require.main === module) main();
module.exports = { portSkill, portFrontmatter, portBody };
